//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "Sinespace_Space.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    Library_Sinespace_Space_Sinespace_Space::HostReport___STATIC__VOID__I4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Sinespace_Space =
{
    "Space",
    0xC39532C7,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
