//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#ifndef SINESPACE_SPACE_H
#define SINESPACE_SPACE_H

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
#include <nanoPackStruct.h>

struct Library_Sinespace_Space_Sinespace_Space
{
    NANOCLR_NATIVE_DECLARE(HostReport___STATIC__VOID__I4);

    //--//
};

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Sinespace_Space;

#endif // SINESPACE_SPACE_H
