set(CMAKE_SYSTEM_NAME WASI)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR wasm32)

find_program(NANOCLR_WASI_CLANG NAMES clang-22 clang-21 clang-20 clang-19 clang-18 clang-17 clang REQUIRED)
find_program(NANOCLR_WASI_CLANGXX NAMES clang++-22 clang++-21 clang++-20 clang++-19 clang++-18 clang++-17 clang++ REQUIRED)

set(CMAKE_C_COMPILER "${NANOCLR_WASI_CLANG}")
set(CMAKE_CXX_COMPILER "${NANOCLR_WASI_CLANGXX}")
set(CMAKE_C_COMPILER_TARGET wasm32-wasi)
set(CMAKE_CXX_COMPILER_TARGET wasm32-wasi)
set(CMAKE_SYSROOT /usr)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_CXX_FLAGS_INIT "-stdlib=libc++")
set(CMAKE_EXECUTABLE_SUFFIX ".wasm")

set(CMAKE_FIND_ROOT_PATH /usr)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
