#ifndef NF_CONFIG_H
#define NF_CONFIG_H

#define CONFIG_NF_ENABLE_DOUBLE_PRECISION_FP 1
#define CONFIG_NF_FEATURE_LIGHT_MATH 1
#define CONFIG_NF_SUPPORT_ANY_BASE_CONVERSION 0
#define CONFIG_NF_FEATURE_DEBUGGER 0
#ifndef CONFIG_NF_FEATURE_SUPPORT_REFLECTION
#define CONFIG_NF_FEATURE_SUPPORT_REFLECTION 0
#endif
#define CONFIG_NF_FEATURE_BINARY_SERIALIZATION 0

#endif
